package: dashboard
<<<<<<< HEAD
version: '2.3.0'
=======
version: '2.2.3'
>>>>>>> 86592c5b1f29c92cb8aca768683a21602cd67239
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfRedaxo/dashboard

page:
    title: 'translate:title'
    perm: dashboard[]
    block: system
    prio: 10
    pjax: true
    icon: rex-icon fas fa-th

#pages:
#    system/log/cronjob:
#        title: Cronjob
#        perm: admin[]

requires:
    php: '>=7.4'
    redaxo: ^5.11.0
