package: dashboard
version: '1.1'
author: 'Robert Rupf, Yakamara Media GmbH & Co. KG'
supportpage: https://github.com/yakamara/dashboard

page:
    title: 'translate:title'
    perm: dashboard[]
    block: system
    prio: 10
    pjax: true
    icon: rex-icon fas fa-th
#    subpages:
#        cronjobs: { title: 'translate:title' }
#        log: { title: 'translate:log' }

#pages:
#    system/log/cronjob:
#        title: Cronjob
#        perm: admin[]

requires:
    php: '>=7.4'
    redaxo: ^5.11.0
