package: dashboard
version: '2.1.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/dashboard

page:
    title: 'translate:title'
    perm: dashboard[]
    block: system
    prio: 10
    pjax: true
    icon: rex-icon fas fa-th

#pages:
#    system/log/cronjob:
#        title: Cronjob
#        perm: admin[]

requires:
    php: '>=7.4'
    redaxo: ^5.11.0
